apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-rs
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cards-demo
  template:
    metadata:
      labels:
        app: cards-demo
    spec:
      containers:
      - name: cards-container
        image: mgorbunov/card-demo:2.0
        ports:
        - containerPort: 8080		