apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-replica
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
      - name: cards-container
        image: mgorbunov/card-demo:2.0
        resources:
            requests:
                cpu: 500m
        ports:
        - containerPort: 8080	
