apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-set
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka
  replicas: 3
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: mgorbunov/eureka
        ports:
        - containerPort: 8080
        env:
        - name: INSTANCES
          value: eureka-0.default, eureka-1.default, eureka-2.default
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 8080
